/* Generated by Report Generator v3.14 (R2013a) */
var gHomeSys = "model_tugas3";
var gNumSys = 3;
var gFrameID = {
"frameset_main":"model_tugas3_slwebview_main_frameset",
"explorer":"model_tugas3_slwebview_explorer",
"frameset_model":"model_tugas3_slwebview_frame",
"model":"model_tugas3_slwebview_model",
"web":"model_tugas3_slwebview_web"};
var gIDMap = {
"model_tugas3":{"target":"slwebview_1.svg","thumb":"slwebview_1_tb.png"},
"model_tugas3/Rangkaian Soal A":{"target":"slwebview_2.svg","thumb":"slwebview_2_tb.png"},
"model_tugas3/Rangkaian Soal B":{"target":"slwebview_3.svg","thumb":"slwebview_3_tb.png"}};

